In [1]:
!unzip '/content/Amazon Product review.zip' -d "/content/"

Archive:  /content/Amazon Product review.zip
  inflating: /content/7817_1.csv     


In [7]:
import pandas as pd


In [8]:
df=pd.read_csv('/content/7817_1.csv')
df

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,NaN,205 grams
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,NaN,205 grams
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,4.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,NaN,NaN,Tedd Gardiner,NaN,NaN,205 grams
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN,NaN,Dougal,NaN,NaN,205 grams
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,NaN,205 grams
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1592,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,3.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,This is not the same remote that I got for my ...,I would be disappointed with myself if i produ...,NaN,NaN,GregAmandawith4,NaN,NaN,4 ounces
1593,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,1.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,I have had to change the batteries in this rem...,Battery draining remote!!!!,NaN,NaN,Amazon Customer,NaN,NaN,4 ounces
1594,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,1.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,"Remote did not activate, nor did it connect to...",replacing an even worse remote. Waste of time,NaN,NaN,Amazon Customer,NaN,NaN,4 ounces
1595,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,3.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,It does the job but is super over priced. I fe...,Overpriced,NaN,NaN,Meg Ashley,NaN,NaN,4 ounces


In [9]:
df['reviews.rating'].value_counts()

,count
reviews.rating,
5.0,741
4.0,236
3.0,124
1.0,42
2.0,34


In [10]:
def sentiment(text):
  if text<3:
    return "Negative"
  elif text==3:
    return "Neutral"
  else:
    return "Positive"

In [11]:
df['reviews.rating']=df['reviews.rating'].apply(sentiment)
df

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,Positive,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,NaN,205 grams
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,Positive,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,NaN,205 grams
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,Positive,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,NaN,NaN,Tedd Gardiner,NaN,NaN,205 grams
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,Positive,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN,NaN,Dougal,NaN,NaN,205 grams
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,Positive,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,NaN,205 grams
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1592,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,Neutral,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,This is not the same remote that I got for my ...,I would be disappointed with myself if i produ...,NaN,NaN,GregAmandawith4,NaN,NaN,4 ounces
1593,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,Negative,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,I have had to change the batteries in this rem...,Battery draining remote!!!!,NaN,NaN,Amazon Customer,NaN,NaN,4 ounces
1594,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,Negative,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,"Remote did not activate, nor did it connect to...",replacing an even worse remote. Waste of time,NaN,NaN,Amazon Customer,NaN,NaN,4 ounces
1595,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,Neutral,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,It does the job but is super over priced. I fe...,Overpriced,NaN,NaN,Meg Ashley,NaN,NaN,4 ounces


In [40]:
df2=df[['reviews.text', 'reviews.rating']].copy()

In [41]:
df2

,reviews.text,reviews.rating
0,I initially had trouble deciding between the p...,Positive
1,Allow me to preface this with a little history...,Positive
2,I am enjoying it so far. Great for reading. Ha...,Positive
3,I bought one of the first Paperwhites and have...,Positive
4,I have to say upfront - I don't like coroporat...,Positive
...,...,...
1592,This is not the same remote that I got for my ...,Neutral
1593,I have had to change the batteries in this rem...,Negative
1594,"Remote did not activate, nor did it connect to...",Negative
1595,It does the job but is super over priced. I fe...,Neutral


In [42]:
df2['reviews.text']=df2['reviews.text'].str.lower()

In [43]:
df2

,reviews.text,reviews.rating
0,i initially had trouble deciding between the p...,Positive
1,allow me to preface this with a little history...,Positive
2,i am enjoying it so far. great for reading. ha...,Positive
3,i bought one of the first paperwhites and have...,Positive
4,i have to say upfront - i don't like coroporat...,Positive
...,...,...
1592,this is not the same remote that i got for my ...,Neutral
1593,i have had to change the batteries in this rem...,Negative
1594,"remote did not activate, nor did it connect to...",Negative
1595,it does the job but is super over priced. i fe...,Neutral


In [44]:
import string
def remove_punc(text):
  return text.translate(str.maketrans('','', string.punctuation))

In [45]:
df2['reviews.text']=df2['reviews.text'].apply(remove_punc)
df2

,reviews.text,reviews.rating
0,i initially had trouble deciding between the p...,Positive
1,allow me to preface this with a little history...,Positive
2,i am enjoying it so far great for reading had ...,Positive
3,i bought one of the first paperwhites and have...,Positive
4,i have to say upfront i dont like coroporate ...,Positive
...,...,...
1592,this is not the same remote that i got for my ...,Neutral
1593,i have had to change the batteries in this rem...,Negative
1594,remote did not activate nor did it connect to ...,Negative
1595,it does the job but is super over priced i fee...,Neutral


In [46]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))

    words = text.split()

    filtered_words = [
        word for word in words
        if word.lower() not in stop_words
    ]

    return " ".join(filtered_words)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [47]:
df2['reviews.text']=df2['reviews.text'].apply(remove_stopwords)
df2

,reviews.text,reviews.rating
0,initially trouble deciding paperwhite voyage r...,Positive
1,allow preface little history casual reader own...,Positive
2,enjoying far great reading original fire since...,Positive
3,bought one first paperwhites pleased constant ...,Positive
4,say upfront dont like coroporate hermetically ...,Positive
...,...,...
1592,remote got alexaecho doesnt control volume thi...,Neutral
1593,change batteries remote twice per month since ...,Negative
1594,remote activate connect boxa poorly designed r...,Negative
1595,job super priced feel like offer replacement r...,Neutral


In [48]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [49]:
wl=WordNetLemmatizer()
def lemmatize(text):
  text=text.split()
  text=[wl.lemmatize(word, pos='v') for word in text]
  return ' '.join(text)

In [50]:
df2['reviews.text']=df2['reviews.text'].apply(lemmatize)
df2

,reviews.text,reviews.rating
0,initially trouble decide paperwhite voyage rev...,Positive
1,allow preface little history casual reader own...,Positive
2,enjoy far great read original fire since 2012 ...,Positive
3,buy one first paperwhites please constant comp...,Positive
4,say upfront dont like coroporate hermetically ...,Positive
...,...,...
1592,remote get alexaecho doesnt control volume thi...,Neutral
1593,change batteries remote twice per month since ...,Negative
1594,remote activate connect boxa poorly design rem...,Negative
1595,job super price feel like offer replacement re...,Neutral


In [53]:
x=df2['reviews.text']
y=df2['reviews.rating']

In [56]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
y=le.fit_transform(y)
y

array([2, 2, 2, ..., 0, 1, 0])

In [57]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.25, random_state=5)

# **First Approach: TFIDF + Logistic Regression**

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [64]:
tf=TfidfVectorizer()

xtrain=tf.fit_transform(x_train).toarray()
xtest=tf.transform(x_test).toarray()

In [65]:
xtrain

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [66]:
from sklearn.linear_model import LogisticRegression

lr=LogisticRegression()


In [67]:
lr.fit(xtrain, y_train)

LogisticRegression()

In [68]:
ypred=lr.predict(xtest)

In [69]:
from sklearn.metrics import accuracy_score

In [71]:
print(accuracy_score(ypred,y_test)*100)

89.25


# **Second Approach: Word2vec + Random Forest**

In [72]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 32.1 MB/s eta 0:00:00


In [75]:
import gensim
from gensim.utils import simple_preprocess
from nltk import sent_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [76]:
data=[]

for word in df2['reviews.text']:
  rs=sent_tokenize(word)
  for s in rs:
    data.append(simple_preprocess(s))

In [77]:
data

[['initially',
  'trouble',
  'decide',
  'paperwhite',
  'voyage',
  'review',
  'less',
  'say',
  'thing',
  'paperwhite',
  'great',
  'spend',
  'money',
  'go',
  'friends',
  'own',
  'end',
  'buy',
  'paperwhite',
  'basis',
  'model',
  'ppi',
  'dollar',
  'jump',
  'turn',
  'pricey',
  'voyage',
  'page',
  'press',
  'isnt',
  'always',
  'sensitive',
  'fine',
  'specific',
  'set',
  'dont',
  'need',
  'auto',
  'light',
  'adjustmentits',
  'week',
  'love',
  'paperwhite',
  'regret',
  'touch',
  'screen',
  'receptive',
  'easy',
  'use',
  'keep',
  'light',
  'specific',
  'set',
  'regardless',
  'time',
  'day',
  'case',
  'hard',
  'change',
  'set',
  'either',
  'youll',
  'change',
  'light',
  'level',
  'certain',
  'time',
  'day',
  'every',
  'readingalso',
  'glad',
  'go',
  'international',
  'ship',
  'option',
  'amazon',
  'extra',
  'expense',
  'delivery',
  'time',
  'track',
  'didnt',
  'need',
  'worry',
  'customs',
  'may',
  'use',
  't

In [78]:
model=gensim.models.Word2Vec(
    window=5
)

In [79]:
model.build_vocab(data)

In [81]:
model.train(data, total_examples=model.corpus_count, epochs=model.epochs)

(568440, 671660)

In [104]:
import numpy as np
def doc_vector(doc):
  doc=[word for word in doc.split() if word in model.wv.index_to_key]
  if len(doc) == 0:
        return np.zeros(model.vector_size)

  return np.mean(model.wv[doc], axis=0)

In [105]:
x1=[]
for doc in df2['reviews.text'].values:
  x1.append(doc_vector(doc))


In [103]:
#sum(df2['reviews.text'].str.strip() == "")

1

In [107]:
x1[0]

array([-0.131214  ,  0.40506428, -0.09965127,  0.108554  ,  0.0906961 ,
       -0.35504833,  0.18113686,  0.7251245 , -0.00347758,  0.01681055,
       -0.0676368 , -0.28989074,  0.08298634, -0.01099036,  0.06203691,
       -0.06011558,  0.31649387, -0.19716331, -0.0992918 , -0.5187703 ,
        0.21316051,  0.06425241,  0.0288099 , -0.37684548, -0.19620074,
       -0.13829866, -0.24751681, -0.21431142, -0.06735421,  0.24955131,
        0.13302392, -0.14974096,  0.00492808, -0.0781674 , -0.11948007,
        0.28996697, -0.03644804, -0.45349383, -0.01915752, -0.3871342 ,
        0.0815255 , -0.4998842 , -0.04040048,  0.10045863,  0.16813259,
       -0.06260138, -0.18454164, -0.06326258,  0.10669718,  0.18905354,
        0.22702166, -0.15061592,  0.0606267 ,  0.23812693, -0.33706   ,
        0.25434855,  0.2215723 ,  0.00992299, -0.29449177,  0.20862661,
       -0.0666228 ,  0.14744677, -0.09333467,  0.16745117,  0.05041554,
        0.3861928 ,  0.13372238, -0.11185363, -0.327495  ,  0.26

In [108]:
y1=y.copy()

In [109]:
y1

array([2, 2, 2, ..., 0, 1, 0])

In [110]:
xtr, xtt, ytr, ytt=train_test_split(x1,y1, test_size=0.2, random_state=5)

In [111]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier()

In [112]:
rf.fit(xtr,ytr)

RandomForestClassifier()

In [113]:
yp=rf.predict(xtt)

In [114]:
print(accuracy_score(yp, ytt))

0.89375
