In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.19.0'

In [4]:
random1=tf.random.Generator.from_seed(5)

# **Normal Distribution**

In [5]:
r1=random1.normal(shape=(3,2))
r1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.0278524 ,  0.27974114],
       [-0.01347923,  1.845181  ],
       [ 0.97061104, -1.0242516 ]], dtype=float32)>

Probability Distribution function

In [6]:
r2=random1.uniform(shape=(3,2))
r2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.76527345, 0.63077855],
       [0.4499545 , 0.7686509 ],
       [0.34525156, 0.62286854]], dtype=float32)>

In [7]:
a=tf.constant([[10,6],
               [4,3],
               [2,5]
])

In [8]:
tf.random.shuffle(a)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  6],
       [ 4,  3]], dtype=int32)>

In [9]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [10]:
tf.zeros([5,5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [11]:
import numpy as np

In [12]:
b=np.arange(1,25, dtype=np.int32)

In [13]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

# **3D tensor**

In [14]:
A=tf.constant(b, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [15]:
2*3*4

24

In [16]:
B=tf.constant(b, shape=(3,8))
B

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

# **Getting Info from Data**

In [17]:
A.shape

TensorShape([2, 3, 4])

In [18]:
B.shape

TensorShape([3, 8])

In [19]:
A.ndim

3

In [20]:
B.ndim

2

In [21]:
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [22]:
tf.size(B)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

# **4D tensor**

In [23]:
t=tf.ones(shape=(2,3,4,5))
t

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [24]:
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [25]:
t[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

# **Tensor Operations**

In [26]:
tensor=tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [27]:
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [28]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [29]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [30]:
tensor / 100

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.1 , 0.07],
       [0.03, 0.04]])>

# **Matrix Multiplication**

In [31]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [32]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [33]:
d=tf.constant([[10,7],
              [4,5],
              [8,9]])


Reshape--> shuffles the element to the desired shape

In [34]:
d1=tf.reshape(d, shape=(2,3))

In [35]:
d1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  4],
       [ 5,  8,  9]], dtype=int32)>

In [36]:
tf.matmul(d,d1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[135, 126, 103],
       [ 65,  68,  61],
       [125, 128, 113]], dtype=int32)>

Transpose--> converts row into columsn and columns into rows

In [37]:
d2=tf.transpose(d)
d2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  4,  8],
       [ 7,  5,  9]], dtype=int32)>

In [38]:
tf.matmul(d,d2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[149,  75, 143],
       [ 75,  41,  77],
       [143,  77, 145]], dtype=int32)>

# **TensorDot**

In [40]:
tf.tensordot(d,tf.transpose(d), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[149,  75, 143],
       [ 75,  41,  77],
       [143,  77, 145]], dtype=int32)>

In [41]:
tf.tensordot(d,tf.reshape(d, shape=(2,3)), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[135, 126, 103],
       [ 65,  68,  61],
       [125, 128, 113]], dtype=int32)>

In [47]:
b.dtype

dtype('int32')

In [45]:
x=tf.constant([1.7,6.9])

In [46]:
x.dtype

tf.float32

In [48]:
x=tf.cast(x, dtype=tf.float16)
x.dtype

tf.float16

# **Aggregating tensors**

In [51]:
y=tf.constant([-7,-9,-10])
y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ -7,  -9, -10], dtype=int32)>

In [52]:
tf.abs(y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7,  9, 10], dtype=int32)>

In [54]:
e=tf.constant(np.random.randint(0,100, size=50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([82, 83, 34,  6,  9, 27, 22, 81, 93, 56, 30, 42, 99, 36, 23, 91,  1,
       42, 24, 35, 80, 58, 58, 20, 17, 38, 85, 83, 60, 72,  1, 62,  1, 88,
       16, 58, 17, 19, 96, 37, 13, 45, 67, 38, 39, 45, 89, 20, 49, 69])>

In [55]:
#find minimum
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [56]:
#find max
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [57]:
#find mean
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [58]:
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2356>

In [62]:
e.dtype

tf.int64

In [65]:
e=tf.cast(e, dtype=tf.float32)
e

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([82., 83., 34.,  6.,  9., 27., 22., 81., 93., 56., 30., 42., 99.,
       36., 23., 91.,  1., 42., 24., 35., 80., 58., 58., 20., 17., 38.,
       85., 83., 60., 72.,  1., 62.,  1., 88., 16., 58., 17., 19., 96.,
       37., 13., 45., 67., 38., 39., 45., 89., 20., 49., 69.],
      dtype=float32)>

In [66]:
tf.math.reduce_variance(e)

<tf.Tensor: shape=(), dtype=float32, numpy=826.545654296875>

In [67]:
tf.math.reduce_std(e)

<tf.Tensor: shape=(), dtype=float32, numpy=28.749706268310547>

In [68]:
tf.random.set_seed(5)
f=tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6263931 , 0.5298432 , 0.7584572 , 0.5084884 , 0.34415376,
       0.31959772, 0.69165003, 0.2665254 , 0.03728402, 0.20195806,
       0.27757192, 0.14514387, 0.2632339 , 0.30723798, 0.3054142 ,
       0.40084064, 0.31193304, 0.90468144, 0.7916621 , 0.75609195,
       0.6157565 , 0.03640282, 0.93310726, 0.7649263 , 0.7422414 ,
       0.02858794, 0.34645987, 0.44837487, 0.46826434, 0.93760514,
       0.49955702, 0.8588258 , 0.56008434, 0.60858595, 0.5712477 ,
       0.57801986, 0.99914443, 0.5327579 , 0.04764938, 0.3474946 ,
       0.33369792, 0.89474916, 0.9426874 , 0.9472102 , 0.10648286,
       0.617066  , 0.8403715 , 0.7066246 , 0.59802914, 0.0299114 ],
      dtype=float32)>

In [70]:
#find positional maximum
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=36>

In [71]:
#Index of largest value position
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.999144434928894>

In [72]:
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.999144434928894>

In [73]:
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=25>

In [74]:
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.028587937355041504>

In [75]:
#tf.squeze

In [78]:
list=[0,1,2,3]

In [79]:
tf.one_hot(list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [80]:
h=tf.range(1,10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [81]:
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [84]:
h=tf.cast(h, dtype=tf.float32)

In [85]:
tf.math.sqrt(h)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [86]:
tf.math.log(h)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [87]:
np.array(h)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)